import Head from 'next/head';
import { motion as m } from 'framer-motion';
import { container, itemParallel } from '../animation';

export default function Home() {
  return (
    <m.div
      initial={{ y: '100%' }}
      animate={{ y: '0%' }}
      exit={{ opacity: 1 }}
      transition={{ duration: 0.75, ease: 'easeOut' }}
      className="text-gray-900 absolute top-0 left-0 w-full h-full bg-orange-100 lg:px-48 px-16"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="my-48 p-1">
          <h1 className="text-6xl text-center lg:text-9xl">Happy Pickle</h1>
        </div>
        <div className="flex justify-between">
          <div>
            <h2>Design</h2>
            <h2>Company</h2>
            <h2>2022</h2>
          </div>
          <m.div variants={container} initial="hidden" animate="show">
            <div className="overflow-hidden">
              <m.h3 variants={itemParallel} initial="hidden" animate="show">
                This pickle gonna make you smile.
              </m.h3>
            </div>
            <div className="overflow-hidden">
              <m.h3 variants={itemParallel}>Scottish designs to make you happy.</m.h3>
            </div>
            <div className="overflow-hidden">
              <m.h3 variants={itemParallel}>Click contact for cool transition.</m.h3>
            </div>
          </m.div>
        </div>
      </main>
    </m.div>
  );
}
