import Head from 'next/head';
import { motion as m } from 'framer-motion';
import { container, itemParallel, page } from '../animation';
import { observer } from 'mobx-react';
import { pageTransitionStore } from '../app/PageTransitionStore';
import { useEffect } from 'react';

const PAGE_BG_COLOR = '#ffedd5'; // bg-orange-100

const HomePage = observer(() => {
  console.log('❗HomePage render', pageTransitionStore.currentColor);

  useEffect(() => {
    pageTransitionStore.setCurrentColor(PAGE_BG_COLOR);
  }, []);

  return (
    <m.div
      className="page text-gray-900 absolute top-0 left-0 w-full h-full lg:px-48 px-16"
      variants={page}
      initial="hidden"
      animate="show"
      exit={{ opacity: 1 }}
      style={{ 'background-color': pageTransitionStore.currentColor, '--bg-new-color': PAGE_BG_COLOR }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="my-48 p-1">
          <m.h1
            className="text-6xl text-center lg:text-9xl"
            initial={{ x: '100%' }}
            animate={{ x: 0 }}
            transition={{ delay: 0.5, duration: 0.5 }}
          >
            Happy Pickle
          </m.h1>
        </div>
        <div className="flex justify-between">
          <div>
            <h2>Design</h2>
            <h2>Company</h2>
            <h2>2022</h2>
          </div>
          <m.div variants={container} initial="hidden" animate="show">
            <div className="overflow-hidden">
              <m.h3 variants={itemParallel} initial="hidden" animate="show">
                This pickle gonna make you smile.
              </m.h3>
            </div>
            <div className="overflow-hidden">
              <m.h3 variants={itemParallel}>Scottish designs to make you happy.</m.h3>
            </div>
            <div className="overflow-hidden">
              <m.h3 variants={itemParallel}>Click contact for cool transition.</m.h3>
            </div>
          </m.div>
        </div>
      </main>
    </m.div>
  );
});

export { HomePage as default };
